[package]
name = "cogware-can"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.1.3"
paste = "1.0.15"
embedded_hal_0_2 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }
mcp2515 = "0.2.2"
strum_macros = "0.26.4"
